name: pixelforge-nexus-server
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production 